# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H5np8cjjH1slZv4pLcKABu1QWQNzveJY
"""

import streamlit as st
import random

st.set_page_config(
    page_title="오늘의 한마디",
    layout="centered",
    initial_sidebar_state="collapsed"
)

st.markdown("""
<style>
.stApp > header {visibility: hidden;}
.stApp > footer {visibility: hidden;}
.stApp [data-testid="stSidebar"] {display: none;}

body {
    background-color: #f0f0f0;
}

.fortune-app-container {
    background-color: white;
    padding: 30px;
    border-radius: 15px;
    box-shadow: 0 4px 15px rgba(0,0,0,0.1);
    text-align: center;
    max-width: 450px;
    margin: 100px auto;
}

div.stButton > button {
    background-color: #DDA0DD;
    color: white;
    padding: 12px 30px;
    border-radius: 8px;
    font-size: 1.1em;
}

.witch-container {
    display: flex;
    justify-content: center;
    align-items: center;
    margin-top: 20px;
}

.witch-figure {
    width: 70px;
    height: 90px;
    background: #4CAF50;
    margin-right: 10px;
    color: white;
    display: flex;
    align-items: center;
    justify-content: center;
}

.speech-bubble {
    background: #FFFAF0;
    padding: 15px;
    border-radius: 10px;
    max-width: 250px;
}
</style>
""", unsafe_allow_html=True)

messages = [
    '오늘 현지와 행복한 시간을 보낼 것 같군요!',
    '오늘은 유독 현지가 많이 보고 싶은 날이군요 ㅜㅜ',
    '이따 현지를 잠깐 만나게 될지도?!',
    '현지가 당신을 많이 사랑하고 있으니, 힘을 내세요.',
    '현지가 당신을 응원하고 있어요! 응원 받아랏!',
    '당신은 행운의 아이콘! 현지도 당신을 사랑해요.',
    '조금 늦어도 괜찮아요, 현지가 있잖아요.',
    '사랑해'
]

if 'show_fortune' not in st.session_state:
    st.session_state.show_fortune = False
if 'current_fortune' not in st.session_state:
    st.session_state.current_fortune = ""

st.markdown('<div class="fortune-app-container">', unsafe_allow_html=True)

if not st.session_state.show_fortune:
    st.markdown("### 오늘의 한마디를 점지해드립니다.")
    if st.button("시작하기"):
        st.session_state.show_fortune = True
        st.session_state.current_fortune = random.choice(messages)
        st.rerun()
else:
    st.markdown(f"""
    <div class="witch-container">
        <div class="witch-figure">Witch</div>
        <div class="speech-bubble">
            {st.session_state.current_fortune}
        </div>
    </div>
    """, unsafe_allow_html=True)

    if st.button("다시 하기"):
        st.session_state.show_fortune = False
        st.rerun()

st.markdown('</div>', unsafe_allow_html=True)