# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H5np8cjjH1slZv4pLcKABu1QWQNzveJY
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile streamlit_fortune_teller.py
# 
# import streamlit as st
# import random
# 
# # Set page configuration
# st.set_page_config(
#     page_title="오늘의 한마디",
#     layout="centered", # Can be "wide" or "centered"
#     initial_sidebar_state="collapsed"
# )
# 
# # Custom CSS for the fortune teller app, including floating icons and button styling
# st.markdown("""
# <style>
#     /* Hide the Streamlit header, footer, and sidebar if present */
#     .stApp > header { visibility: hidden; }
#     .stApp > footer { visibility: hidden; }
#     .stApp [data-testid="stSidebar"] { display: none; }
# 
#     /* Basic styling for the entire app area to center content and set background */
#     .stApp {
#         display: flex;
#         flex-direction: column;
#         justify-content: center;
#         align-items: center;
#         min-height: 100vh; /* Use viewport height */
#         margin: 0;
#         font-family: 'Malgun Gothic', 'Apple SD Gothic Neo', Arial, sans-serif;
#         background-color: #f0f0f0; /* Light gray background */
#         position: relative;
#         overflow: hidden; /* For floating icons */
#     }
# 
#     /* Container for the main interactive content (card-like) */
#     .fortune-app-container {
#         background-color: white;
#         padding: 30px;
#         border-radius: 15px;
#         box-shadow: 0 4px 15px rgba(0, 0, 0, 0.1);
#         text-align: center;
#         position: relative;
#         z-index: 10; /* Ensure it's above floating icons */
#         width: 100%;
#         max_width: 450px;
#         box-sizing: border-box;
#         margin: auto; /* Center the container horizontally */
#     }
# 
#     h1 {
#         color: #333;
#         font-size: 1.8em;
#         margin-bottom: 20px;
#     }
# 
#     /* Streamlit button custom styling */
#     div.stButton > button {
#         background-color: #DDA0DD; /* Light purple / Plum */
#         color: white;
#         padding: 12px 30px;
#         border: none;
#         border-radius: 8px;
#         font-size: 1.2em;
#         cursor: pointer;
#         transition: background-color 0.3s ease, transform 0.1s ease;
#         box-shadow: 0 3px 6px rgba(0, 0, 0, 0.2);
#     }
# 
#     div.stButton > button:hover {
#         background-color: #CC99CC; /* Slightly darker purple on hover */
#         transform: translateY(-2px);
#     }
#     div.stButton > button:active {
#         transform: translateY(0);
#         box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
#     }
# 
#     /* Witch and Speech Bubble layout */
#     .witch-container {
#         display: flex;
#         align-items: flex-end; /* Align witch and bubble at the bottom */
#         justify-content: center;
#         margin-top: 20px;
#     }
# 
#     /* Placeholder for Minecraft Witch */
#     .witch-figure {
#         width: 80px;
#         height: 100px;
#         background-color: #4CAF50; /* Green color */
#         border-radius: 5px;
#         position: relative;
#         margin-right: 15px;
#         color: white;
#         font-size: 0.7em;
#         display: flex;
#         align-items: center;
#         justify-content: center;
#         text-align: center;
#         font-weight: bold;
#         flex-shrink: 0;
#         border: 2px solid #388E3C;
#     }
#     .witch-figure::before { /* Hat */
#         content: '';
#         position: absolute;
#         top: -20px;
#         left: 50%;
#         transform: translateX(-50%);
#         width: 0;
#         height: 0;
#         border-left: 25px solid transparent;
#         border-right: 25px solid transparent;
#         border-bottom: 25px solid #6D4C41; /* Brown hat */
#         z-index: 1;
#     }
#     .witch-figure::after { /* Hat brim */
#         content: '';
#         position: absolute;
#         top: -5px;
#         left: 50%;
#         transform: translateX(-50%);
#         width: 60px;
#         height: 10px;
#         background-color: #6D4C41; /* Brown hat */
#         border-radius: 2px;
#         z-index: 0;
#     }
# 
#     .speech-bubble {
#         position: relative;
#         background: #FFFAF0; /* Floral White */
#         border-radius: .8em;
#         padding: 15px 20px;
#         text-align: left;
#         max-width: 280px;
#         min_height: 50px;
#         display: flex;
#         align-items: center;
#         justify-content: center;
#         font-size: 1.1em;
#         color: #333;
#         box-shadow: 0 2px 8px rgba(0,0,0,0.1);
#         line-height: 1.4;
#     }
# 
#     .speech-bubble:before { /* Tail of the speech bubble */
#         content: '';
#         position: absolute;
#         left: 0;
#         top: 50%;
#         width: 0;
#         height: 0;
#         border: 15px solid transparent;
#         border-right-color: #FFFAF0;
#         border-left: 0;
#         margin-top: -15px;
#         margin-left: -15px;
#     }
# 
#     /* Floating icons background simulation */
#     .floating-background {
#         position: fixed; /* Fixed position relative to viewport */
#         top: 0;
#         left: 0;
#         width: 100vw; /* Full viewport width */
#         height: 100vh; /* Full viewport height */
#         pointer-events: none; /* Allow clicks to pass through */
#         z-index: 1; /* Below the main app content */
#         overflow: hidden; /* Hide icons if they go outside */
#     }
# 
#     .floating-icon {
#         position: absolute;
#         background-color: rgba(255, 192, 203, 0.4); /* Pinkish bubble */
#         border-radius: 50%;
#         animation: float 12s infinite ease-in-out;
#         opacity: 0.6;
#         box-shadow: 0 0 10px rgba(255, 192, 203, 0.5);
#     }
# 
#     .floating-icon:nth-child(1) { width: 30px; height: 30px; top: 10%; left: 15%; animation-duration: 10s; animation-delay: 0s; }
#     .floating-icon:nth-child(2) { width: 40px; height: 40px; background-color: rgba(173, 216, 230, 0.4); top: 60%; left: 80%; animation-duration: 12s; animation-delay: 2s; }
#     .floating-icon:nth-child(3) { width: 25px; height: 25px; background-color: rgba(255, 255, 0, 0.4); top: 30%; left: 50%; animation-duration: 9s; animation-delay: 4s; }
#     .floating-icon:nth-child(4) { width: 35px; height: 35px; background-color: rgba(144, 238, 144, 0.4); top: 80%; left: 25%; animation-duration: 11s; animation-delay: 1s; }
#     .floating-icon:nth-child(5) { width: 20px; height: 20px; background-color: rgba(221, 160, 221, 0.4); top: 40%; left: 5%; animation-duration: 8s; animation-delay: 3s; }
#     .floating-icon:nth-child(6) { width: 45px; height: 45px; background-color: rgba(255, 99, 71, 0.4); top: 25%; left: 90%; animation-duration: 13s; animation-delay: 5s; }
#     .floating-icon:nth-child(7) { width: 30px; height: 30px; background-color: rgba(135, 206, 235, 0.4); top: 5%; left: 60%; animation-duration: 10.5s; animation-delay: 0.5s; }
# 
#     @keyframes float {
#         0% { transform: translate(0, 0) scale(1); opacity: 0.6; }
#         25% { transform: translate(20px, -20px) scale(1.05); opacity: 0.8; }
#         50% { transform: translate(-20px, 0) scale(0.95); opacity: 0.6; }
#         75% { transform: translate(10px, 20px) scale(1.1); opacity: 0.8; }
#         100% { transform: translate(0, 0) scale(1); opacity: 0.6; }
#     }
# </style>
# """, unsafe_allow_html=True)
# 
# # Inject floating background elements
# st.markdown("""
#     <div class="floating-background">
#         <div class="floating-icon"></div>
#         <div class="floating-icon"></div>
#         <div class="floating-icon"></div>
#         <div class="floating-icon"></div>
#         <div class="floating-icon"></div>
#         <div class="floating-icon"></div>
#         <div class="floating-icon"></div>
#     </div>
# """, unsafe_allow_html=True)
# 
# 
# messages = [
#     '오늘 현지와 행복한 시간을 보낼 것 같군요!',
#     '오늘은 유독 현지가 많이 보고 싶은 날이군요 ㅜㅜ',
#     '이따 현지를 잠깐 만나게 될지도?!',
#     '현지가 당신을 많이 사랑하고 있으니, 힘을 내세요.',
#     '현지가 당신을 응원하고 있어요! 응원 받아랏!',
#     '당신은 행운의 아이콘! 현지도 당신을 사랑해요.',
#     '조금 늦어도 괜찮아요, 현지가 있잖아요.',
#     '사랑해'
# ]
# 
# # Initialize session state for fortune display
# if 'show_fortune' not in st.session_state:
#     st.session_state.show_fortune = False
# if 'current_fortune' not in st.session_state:
#     st.session_state.current_fortune = ""
# 
# # Main content goes into a centered container
# with st.container():
#     st.markdown('<div class="fortune-app-container">', unsafe_allow_html=True)
# 
#     if not st.session_state.show_fortune:
#         st.markdown("<h1>오늘의 한마디를 점지해드립니다.</h1>", unsafe_allow_html=True)
#         if st.button("시작하기", key="start_button"):
#             st.session_state.show_fortune = True
#             st.session_state.current_fortune = random.choice(messages)
#             st.rerun() # Rerun to show message screen
#     else:
#         # Message screen
#         st.markdown(f"""
#             <div class="witch-container">
#                 <div class="witch-figure">Witch</div>
#                 <div class="speech-bubble">
#                     <span id="fortune-text">{st.session_state.current_fortune}</span>
#                 </div>
#             </div>
#         """, unsafe_allow_html=True)
#         if st.button("다시 하기", key="reset_button"):
#             st.session_state.show_fortune = False
#             st.session_state.current_fortune = "" # Clear message
#             st.rerun() # Rerun to show welcome screen
# 
#     st.markdown('</div>', unsafe_allow_html=True)